sudo apt-get update ;
sudo apt-get -y install git ;
sudo apt-get -y install curl ;
sudo apt-get -y install python-software-properties ;
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - ;
sudo apt-get -y install nodejs ;
npm install -g pm2;
rm -rf proxy-master;
git clone https://github.com/danoctavian/proxy-master.git ;
cd proxy-master ;
npm install;